const topScorersList = [
  { team: 'Argentina', players: ['Lionel Messi', 'Julián Álvarez', 'Lautaro Martínez', 'Ángel Di María', 'Paulo Dybala'] },
  { team: 'Brazil', players: ['Vinícius Jr', 'Neymar', 'Rodrygo', 'Richarlison', 'Gabriel Martinelli'] },
  { team: 'France', players: ['Kylian Mbappé', 'Antoine Griezmann', 'Olivier Giroud', 'Ousmane Dembélé', 'Marcus Thuram'] },
  { team: 'England', players: ['Harry Kane', 'Bukayo Saka', 'Jude Bellingham', 'Phil Foden', 'Cole Palmer'] },
  { team: 'Spain', players: ['Lamine Yamal', 'Álvaro Morata', 'Nico Williams', 'Pedri', 'Dani Olmo'] },
  { team: 'Germany', players: ['Jamal Musiala', 'Niclas Füllkrug', 'Florian Wirtz', 'Kai Havertz', 'Serge Gnabry'] },
  { team: 'Netherlands', players: ['Memphis Depay', 'Cody Gakpo', 'Donyell Malen', 'Xavi Simons', 'Wout Weghorst'] },
  { team: 'Portugal', players: ['Cristiano Ronaldo', 'Bruno Fernandes', 'Diogo Jota', 'João Félix', 'Gonçalo Ramos'] },
  { team: 'Belgium', players: ['Romelu Lukaku', 'Kevin De Bruyne', 'Jérémy Doku', 'Lois Openda', 'Leandro Trossard'] },
  { team: 'Croatia', players: ['Luka Modrić', 'Andrej Kramarić', 'Bruno Petković', 'Ivan Perišić', 'Mario Pašalić'] },
  { team: 'Uruguay', players: ['Darwin Núñez', 'Federico Valverde', 'Facundo Pellistri', 'Brian Rodríguez', 'Luis Suárez'] },
  { team: 'Colombia', players: ['Luis Díaz', 'James Rodríguez', 'Rafael Santos Borré', 'Jhon Arias', 'Jhon Durán'] },
  { team: 'Morocco', players: ['Achraf Hakimi', 'Youssef En-Nesyri', 'Hakim Ziyech', 'Sofyan Amrabat', 'Ayoub El Kaabi'] },
  { team: 'Senegal', players: ['Sadio Mané', 'Ismaïla Sarr', 'Nicolas Jackson', 'Habib Diallo', 'Pape Matar Sarr'] },
  { team: 'Japan', players: ['Daichi Kamada', 'Takefusa Kubo', 'Kyogo Furuhashi', 'Ritsu Doan', 'Ayase Ueda'] },
  { team: 'South Korea', players: ['Son Heung-min', 'Hwang Hee-chan', 'Lee Kang-in', 'Cho Gue-sung', 'Oh Hyeon-gyu'] },
  { team: 'Switzerland', players: ['Breel Embolo', 'Xherdan Shaqiri', 'Noah Okafor', 'Zeki Amdouni', 'Dan Ndoye'] },
  { team: 'Denmark', players: ['Rasmus Højlund', 'Christian Eriksen', 'Kasper Dolberg', 'Mikkel Damsgaard', 'Andreas Skov Olsen'] },
  { team: 'Mexico', players: ['Santiago Giménez', 'Raúl Jiménez', 'Hirving Lozano', 'Julián Quiñones', 'Uriel Antuna'] },
  { team: 'USA', players: ['Christian Pulišić', 'Weston McKennie', 'Folarin Balogun', 'Tim Weah', 'Ricardo Pepi'] },
  { team: 'Canada', players: ['Alphonso Davies', 'Jonathan David', 'Cyle Larin', 'Tajon Buchanan', 'Liam Millar'] },
  { team: 'Ecuador', players: ['Enner Valencia', 'Kendry Páez', 'Ángel Mena', 'Kevin Rodríguez', 'Alan Minda'] },
  { team: 'Paraguay', players: ['Miguel Almirón', 'Antonio Sanabria', 'Ángel Romero', 'Alejandro Romero', 'Ramón Sosa'] },
  { team: 'Australia', players: ['Mitchell Duke', 'Craig Goodwin', 'Riley McGree', 'Martin Boyle', 'Mathew Leckie'] },
  { team: 'Sweden', players: ['Alexander Isak', 'Viktor Gyökeres', 'Dejan Kulusevski', 'Emil Forsberg', 'Anthony Elanga'] },
  { team: 'Norway', players: ['Erling Haaland', 'Alexander Sørloth', 'Martin Ødegaard', 'Jørgen Strand Larsen', 'Ola Solbakken'] },
  { team: 'Poland', players: ['Robert Lewandowski', 'Karol Świderski', 'Kamil Grosicki', 'Jakub Kamiński', 'Sebastian Szymański'] },
  { team: 'Austria', players: ['Marko Arnautović', 'Christoph Baumgartner', 'Michael Gregoritsch', 'Andreas Weimann', 'Romano Schmid'] },
  { team: 'Turkey', players: ['Hakan Çalhanoğlu', 'Kerem Aktürkoğlu', 'Barış Alper Yılmaz', 'Bertuğ Yıldırım', 'Yusuf Yazıcı'] },
  { team: 'Egypt', players: ['Mohamed Salah', 'Omar Marmoush', 'Mostafa Mohamed', 'Mahmoud Trezeguet', 'Ahmed Sayed'] },
  { team: 'Tunisia', players: ['Wahbi Khazri', 'Seifeddine Jaziri', 'Youssef Msakni', 'Elias Achouri', 'Naïm Sliti'] },
  { team: 'Algeria', players: ['Riyad Mahrez', 'Islam Slimani', 'Said Benrahma', 'Baghdad Bounedjah', 'Yacine Brahimi'] },
  { team: 'Nigeria', players: ['Victor Osimhen', 'Samuel Chukwueze', 'Ademola Lookman', 'Kelechi Iheanacho', 'Taiwo Awoniyi'] },
  { team: 'Ivory Coast', players: ['Sébastien Haller', 'Jérémie Boga', 'Jonathan Bamba', 'Jean-Philippe Krasso', 'Seko Fofana'] },
  { team: 'Ghana', players: ['Mohammed Kudus', 'Iñaki Williams', 'Antoine Semenyo', 'Jordan Ayew', 'Ernest Nuamah'] },
  { team: 'Cameroon', players: ['Vincent Aboubakar', 'Bryan Mbeumo', 'Karl Toko Ekambi', 'Eric Choupo-Moting', 'Georges-Kévin Nkoudou'] },
  { team: 'South Africa', players: ['Percy Tau', 'Lyle Foster', 'Themba Zwane', 'Evidence Makgopa', 'Monnapule Saleng'] },
  { team: 'Congo DR', players: ['Cédric Bakambu', 'Yoane Wissa', 'Théo Bongonda', 'Simon Banza', 'Samuel Moutoussamy'] },
  { team: 'Scotland', players: ['John McGinn', 'Scott McTominay', 'Che Adams', 'Lawrence Shankland', 'Ryan Christie'] },
  { team: 'Iran', players: ['Sardar Azmoun', 'Mehdi Taremi', 'Alireza Jahanbakhsh', 'Saman Ghoddos', 'Mohammad Mohebi'] },
  { team: 'Iraq', players: ['Aymen Hussein', 'Ali Jasim', 'Zidane Iqbal', 'Mohamed Ali', 'Ibrahim Bayesh'] },
  { team: 'Saudi Arabia', players: ['Salem Al-Dawsari', 'Firas Al-Buraikan', 'Saleh Al-Shehri', 'Abdullah Al-Hamdan', 'Ayman Yahya'] },
  { team: 'Qatar', players: ['Akram Afif', 'Almoez Ali', 'Mehdi Ali', 'Al-Hassan Al-Haydos', 'Yusuf Abdurisag'] },
  { team: 'Uzbekistan', players: ['Eldor Shomurodov', 'Oston Urunov', 'Khusayin Norchaev', 'Azizbek Turgunboev', 'Abbosbek Fayzullaev'] },
  { team: 'Jordan', players: ['Ali Olwan', 'Hamza Al-Dardour', 'Yazan Al-Naimat', 'Mousa Al-Tamari', 'Nizar Al-Rashdan'] },
  { team: 'New Zealand', players: ['Chris Wood', 'Ben Waine', 'Logan Rogerson', 'Jesse Randall', 'Marko Stamenić'] },
  { team: 'Cape Verde Islands', players: ['Jovane Cabral', 'Jorge Semedo', 'Gilson Tavares', 'Duk Lima', 'Rúben Ramos'] },
  { team: 'Haiti', players: ['Duckens Nazon', 'Carnejy Antoine', 'Frandy Montrévil', 'Danley Jean-Jacques', 'Frédéric Piquionne'] },
  { team: 'Panama', players: ['Ismael Díaz', 'José Fajardo', 'Yahya Martínez', 'Gabriel Torres', 'Rolando Blackburn'] },
  { team: 'Bosnia-Herzegovina', players: ['Edin Džeko', 'Rade Krunić', 'Ermedin Demirović', 'Haris Hajradinović', 'Benjamin Tahirović'] },
  { team: 'Czechia', players: ['Patrik Schick', 'Tomáš Souček', 'Jan Kuchta', 'Adam Hložek', 'Václav Černý'] },
  { team: 'Curaçao', players: ['Xander Severina', 'Bernard Schoop', 'Juninho Bacuna', 'Rangelo Janga', 'Daylon Claasen'] },
  { team: 'Peru', players: ['Gianluca Lapadula', 'Paolo Guerrero', 'Yordy Reyna', 'Bryan Reyna', 'Joao Grimaldo'] },
  { team: 'Chile', players: ['Eduardo Vargas', 'Darío Osorio', 'Santiago Damián', 'Cristian Palacios', 'Luciano Cabral'] },
];

export function getAllPlayers() {
  return topScorersList.flatMap((entry) => entry.players);
}

export function getPlayerSuggestions() {
  return topScorersList;
}
